name: Build and push an image to ECR public

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: b1o7r7e0/frontend           # set this to your Amazon ECR repository name

permissions:
  id-token: write
  contents: read

jobs:
  push:
    name: Push Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          role-to-assume: "arn:aws:iam::601427279990:role/AoTo-gh-ecr-push-role"
          role-session-name: MySessionName

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
        with:
          registry-type: public

      - name: Build and push docker image to ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "b1o7r7e0/frontend"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
      - name: Checkout Kubernetes manifests repo
        uses: actions/checkout@v3
        with:
          repository: dd-japan/frontend-manifest
          token: ${{ secrets.CICD_GH_TOKEN }}
          path: frontend-manifest

      - name: List files for debugging
        run: ls -R frontend-manifest
        
      - name: Update Deployment manifests
        run: |
            sed -i 's|image: public.ecr.aws/b1o7r7e0/frontend:[^[:space:]]*|image: public.ecr.aws/b1o7r7e0/frontend:${{ github.sha }}|g' frontend-manifest/manifest/frontend.yaml
            cat frontend-manifest/manifest/frontend.yaml

      - name: Commit and push changes
        working-directory: frontend-manifest
        run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"
            git add manifest/frontend.yaml
            git status
            git commit -m "Update image to public.ecr.aws/b1o7r7e0/frontend:${{ env.IMAGE_TAG }}"
            git push origin main
